### ISSUE TITLE
Sharing iP code quality feedback [for @teoyuqi]

### ISSUE THREAD

**Issue by soc-se-bot-blue** [teoyuqi/ip#3]
@teoyuqi We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

Example from [`src/main/java/duke/Duke.java` lines `34-34`](https://github.com/teoyuqi/ip/blob/eb492237d0df1a63bb435510171e1be8fd0fc2d4/src/main/java/duke/Duke.java#L34..L34):

```java

    private boolean dukeIsRunning = false;

```

Example from [`src/main/java/duke/Parser.java` lines `330-330`](https://github.com/teoyuqi/ip/blob/eb492237d0df1a63bb435510171e1be8fd0fc2d4/src/main/java/duke/Parser.java#L330..L330):

```java

        Boolean taskNumberIsNegativeOrZero = taskNumber <= 0;

```

Example from [`src/main/java/duke/Parser.java` lines `331-331`](https://github.com/teoyuqi/ip/blob/eb492237d0df1a63bb435510171e1be8fd0fc2d4/src/main/java/duke/Parser.java#L331..L331):

```java

        Boolean taskNumberIsLargerThanTaskCount = taskNumber > size;

``` 

**Suggestion:** Follow the given naming convention for boolean variables/methods (e.g., use a boolean-sounding prefix).You may ignore the above if you think the name already follows the convention (the script can report false positives in some cases)

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/TaskList.java` lines `214-217`](https://github.com/teoyuqi/ip/blob/eb492237d0df1a63bb435510171e1be8fd0fc2d4/src/main/java/duke/TaskList.java#L214..L217):

```java

    /**
     * Return {@code TaskList} as format to be saved in hard disk.
     * @return String of {@code TaskList} as format to be saved in file.
     */

```

Example from [`src/main/java/duke/task/Deadline.java` lines `51-56`](https://github.com/teoyuqi/ip/blob/eb492237d0df1a63bb435510171e1be8fd0fc2d4/src/main/java/duke/task/Deadline.java#L51..L56):

```java

    /**
     * To produce a {@code String} with "|" delimiters for storing the
     * {@code Deadline}'s data in a text file.
     * @return "deadline|[COMPLETION STATUS]|[TASK DESCRIPTION]
     *                  |[PRIORITY][TASK DEADLINE]"
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by teoyuqi** [comment]
## Above errors have been corrected in the commits specified below:
* Incorrect naming of `Boolean` variables has been corrected in [commit cccec47](https://github.com/teoyuqi/ip/commit/cccec47edf6903a30b699f37e443f689bca661f2).
* Incorrect header comments have been corrected in [commit 332fa9b](https://github.com/teoyuqi/ip/commit/332fa9bbe86f575e38c0022b12f24912eb9c8133).
